
filebeat.inputs:

- type: log
  paths:
  - /var/log/info/*.log
  fields: 
    agent_type: filebeat
    log_type: info
  fields_under_root: true 
    
- type: log
  paths:
  - /var/log/error/*.log
  fields: 
    agent_type: filebeat
    log_type: error
  fields_under_root: true   

output.logstash:

  # The Logstash hosts

  hosts: ["logstash:5000"]